In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv",encoding='ISO-8859-1')
df.head(5)

category                                            message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
new_df=[feature for feature in df.columns if df[feature].isnull().sum()]
new_df

['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

In [4]:
df.drop(new_df,axis=1,inplace=True)

In [5]:
df

category                                            message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
def new_col(x):
    if x=="spam":
        return 1
    return 0

In [7]:
df["spam"]=df["category"].apply(new_col)

In [8]:
df

category                                            message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham              Will Ì_ b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.message,df.spam,test_size=.3)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

v=CountVectorizer()

X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<3900x7202 sparse matrix of type '<class 'numpy.int64'>'
	with 51785 stored elements in Compressed Sparse Row format>

In [11]:
X_train_cv.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
X_train.values

array(["it's still not working. And this time i also tried adding zeros. That was the savings. The checking is  &lt;#&gt; ",
       ', ,  and  picking them up from various points | going 2 yeovil | and they will do the motor project 4 3 hours | and then u take them home. || 12 2 5.30 max. || Very easy',
       'Hiya, probably coming home * weekend after next', ...,
       'Do you like shaking your booty on the dance floor?',
       'Ok anyway no need to change with what you said',
       'You have won ?1,000 cash or a ?2,000 prize! To claim, call09050000327. T&C: RSTM, SW7 3SS. 150ppm'],
      dtype=object)

In [28]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
len(v.vocabulary_)


7202

In [15]:
np.where(X_train_np!=0)

(array([   0,    0,    0, ..., 3899, 3899, 3899], dtype=int64),
 array([ 744,  849,  876, ..., 6431, 7029, 7153], dtype=int64))

In [16]:
v.get_feature_names()[5417]

'rummer'

In [17]:
# v.vocabulary_

In [19]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [22]:
X_test_cv=v.transform(X_test)

In [23]:
# y_pred=model.predict(X_test_cv)

In [29]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1433
           1       0.97      0.92      0.94       239

    accuracy                           0.98      1672
   macro avg       0.98      0.96      0.97      1672
weighted avg       0.98      0.98      0.98      1672



In [30]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)